block_cipher = None

a = Analysis(
    ['cli/main.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'prompt_toolkit',
        'prompt_toolkit.history',
        'prompt_toolkit.styles',
        'prompt_toolkit.formatted_text',
        'keyring.backends',
        'keyring.backends.macOS',
        'keyring.backends.Windows',
        'keyring.backends.SecretService',
        'anthropic',
        'openai',
        'google.generativeai',
        'elio',
        'elio.cli',
        'elio.auth',
        'elio.config',
        'elio.providers',
        'elio.session',
        'elio.files',
        'elio.utils'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='elio',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)